version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      SERVICES: s3,sqs,sns,lambda,dynamodb,apigateway
      DEFAULT_REGION: sa-east-1
      AWS_ACCESS_KEY_ID: accessKeyId
      AWS_SECRET_ACCESS_KEY: secretAccessKey
      AWS_SECURITY_TOKEN: securityToken
    ports:
      - '4566:4566'
    volumes:
      - "./entrypoint.d:/docker-entrypoint-initaws.d"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    networks:
      - localstack-network

networks:
  localstack-network:
    name: localstack-network